version: "3"
services:
  service_node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ${NEDB_DIRECTORY}
    - ${TEMPORARY_FILES_DIRECTORY}
    - ${DDS_STUB_FILES_DIRECTORY}
    ports:
    - ${SERVICE_NODE_API_PORT}:${SERVICE_NODE_API_PORT}
    - ${BOOTSTRAP_NODE_PORT}:${BOOTSTRAP_NODE_PORT}
    network_mode: host
