version: "3"
services:
  service_node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/usr/src/app
    ports:
    - ${SERVICE_NODE_API_PORT}:${SERVICE_NODE_API_PORT}
    - ${BOOTSTRAP_NODE_PORT}:${BOOTSTRAP_NODE_PORT}
